name: Build Windows App
on:
  workflow_dispatch:
jobs:
  win:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: windows-app
    env:
      CSC_IDENTITY_AUTO_DISCOVERY: "false"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Show folder (debug)
        shell: bash
        run: ls -la && ls -la build
      - run: npm install
      - run: npm run build:win
      - uses: actions/upload-artifact@v4
        with:
          name: YouTrix-windows
          path: windows-app/dist/*.exe
